"""默认内置斜杠命令。"""

from __future__ import annotations

from okcode.commands.handlers import (
    clear_command,
    compact_command,
    do_command,
    exit_command,
    help_command,
    hooks_command,
    memory_command,
    permission_command,
    plan_command,
    resume_command,
    review_command,
    session_command,
    skill_command,
    status_command,
    tasks_command,
    team_command,
)
from okcode.commands.models import CommandDefinition, CommandKind
from okcode.commands.registry import CommandRegistry


def build_default_command_registry() -> CommandRegistry:
    """构造内置命令的注册中心。"""

    return CommandRegistry(
        (
            CommandDefinition(
                "exit",
                (),
                "关闭 TUI 进程。",
                "/exit",
                CommandKind.UI,
                None,
                False,
                exit_command,
            ),
            CommandDefinition(
                "plan",
                (),
                "切换到计划模式。",
                "/plan",
                CommandKind.UI,
                None,
                False,
                plan_command,
            ),
            CommandDefinition(
                "do",
                (),
                "执行当前会话最近一次计划。",
                "/do",
                CommandKind.PROMPT,
                None,
                False,
                do_command,
            ),
            CommandDefinition(
                "compact",
                (),
                "手动压缩当前上下文。",
                "/compact",
                CommandKind.UI,
                None,
                False,
                compact_command,
            ),
            CommandDefinition(
                "resume",
                (),
                "恢复一个历史会话。",
                "/resume",
                CommandKind.UI,
                None,
                False,
                resume_command,
            ),
            CommandDefinition(
                "clear",
                (),
                "结束当前会话并开启新会话。",
                "/clear",
                CommandKind.UI,
                None,
                False,
                clear_command,
            ),
            CommandDefinition(
                "help",
                (),
                "显示可用命令。",
                "/help",
                CommandKind.LOCAL,
                None,
                False,
                help_command,
            ),
            CommandDefinition(
                "status",
                (),
                "显示当前运行状态。",
                "/status",
                CommandKind.LOCAL,
                None,
                False,
                status_command,
            ),
            CommandDefinition(
                "memory",
                (),
                "列出已加载记忆文件。",
                "/memory",
                CommandKind.LOCAL,
                None,
                False,
                memory_command,
            ),
            CommandDefinition(
                "permission",
                (),
                "显示或修改当前权限模式。",
                "/permission [strict|default|allow]",
                CommandKind.LOCAL,
                "strict|default|allow",
                False,
                permission_command,
            ),
            CommandDefinition(
                "hooks",
                (),
                "列出已加载 Hook 规则。",
                "/hooks",
                CommandKind.LOCAL,
                None,
                False,
                hooks_command,
            ),
            CommandDefinition(
                "tasks",
                (),
                "列出或控制后台子 Agent 任务。",
                "/tasks [cancel|background <task_id>]",
                CommandKind.LOCAL,
                None,
                False,
                tasks_command,
            ),
            CommandDefinition(
                "team",
                (),
                "创建、恢复或查询 Team Lead 小组。",
                "/team [create|use|leave|status <name>]",
                CommandKind.LOCAL,
                "create|use|leave|status",
                False,
                team_command,
            ),
            CommandDefinition(
                "session",
                (),
                "显示当前会话标识。",
                "/session",
                CommandKind.LOCAL,
                None,
                False,
                session_command,
            ),
            CommandDefinition(
                "skill",
                (),
                "列出可加载和已激活的 Skill。",
                "/skill",
                CommandKind.LOCAL,
                None,
                False,
                skill_command,
            ),
            CommandDefinition(
                "review",
                (),
                "请求代码审查。",
                "/review",
                CommandKind.PROMPT,
                None,
                False,
                review_command,
            ),
        )
    )
